name: sonarqube-bosh

releases:
- name: sonarqube-bosh
  version: latest

stemcells:
- alias: default
  os: ubuntu-trusty
  version: latest

update:
  canaries: 1
  max_in_flight: 1
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000

instance_groups:
- name: sonarqube
  azs:
  - z1
  instances: 1
  jobs:
  - name: sonarqube
    release: sonarqube-bosh
    properties: {}
  vm_type: g1-small
  stemcell: default
  networks:
  - name: default
    static_ips:
    - 10.0.0.11
